TwentyBN/sense

README.md, requirements.txt, scripts/conversion/cfg/efficientnet.cfg, scripts/conversion/cfg/logistic_regression.cfg, scripts/conversion/convert_to_coreml.py
This PR contains @marktodorovich's conversion script. Main difference with the original version is that I changed which parameters are exposed or hardcoded and I did some small refactoring changes early in the script, before the config file is parsed, so that it is possible to combine a generic backbone network with a specific classifier. After the config file is parsed, everything is pretty much the same.
Here is how to use it:
```
python scripts/conversion/convert_to_coreml.py --backbone=efficientnet --classifier=efficient_net_gesture_control --output_name=efficientnet_gesture_control --float16
```
For now, `--backbone=efficientnet` and `--classifier=efficient_net_gesture_control` are the only available options but it should be straightforward to later add support to more backbone …
=> Add a coreml conversion script 

realtimenet/display.py
This PR adds documentation to the entire `display.py` file. It also refactors and abstracts a `BaseDisplay` class for subclasses to inherit, which makes type hinting easier.
=> Documentation/Refactor - display.py

requirements.txt
This PR will change the `requirement.txt` in which the `h5py==2.10.0` is added. It will resolve the error of coreml conversion because KerasAPI does not support h5py>3.0.0.
=> Fix: coreml conversion script

realtimenet/controller.py, realtimenet/downstream_tasks/nn_utils.py, realtimenet/engine.py, realtimenet/feature_extractors/mobilenet.py
Per Guillaume's comment:
The parameter inside `Controller` class: `neural_network: nn.Module` might have a misleading type hint because not every `nn.Module` will work as a parameter for `InferenceEngine` expects those with certain attributes/methods (`net.fps`, `net.step_size`, `net.preprocess` etc...). We should create an abstract `RealtimeNeuralNet` class that clarifies the requirements.
=> Abstract Neural Network Class to replace nn.Module as type hint

README.md
For the folder structures in README, use the formatting that is also output by the `tree` command.
=> Format folder structures in `tree` style

scripts/tools/video_capture.py
- Ticket: [AV-3982](https://20bn.atlassian.net/browse/AV-3982)
This PR fixes the error while recording video using `video_capture.py`. Earlier, the horizontally flipped video being previewed was the one being saved as well, but that isn't the desired behavior. This PR will update that to only preview the flipped video, but record the original (unflipped) version.
=> [Video Capture] Preview mirrored video but save original

scripts/tools/annotation/templates/up_list.html
In the current `master` version, the `1` button isn't clickable, because the ID has a typo.
=> Fix ID for second label radio button

scripts/tools/annotation/templates/up_list.html
1. The link for `train_logreg` was broken
2. The "Export annotations" button seems outdated, because the `/export_annotation` endpoint no longer exists. The functionality is now probably covered by the submit button on the main form.
=> Fix annotation buttons

scripts/run_calorie_estimation.py, scripts/run_custom_classifier.py, scripts/run_fitness_rep_counter.py, scripts/run_fitness_tracker.py, scripts/run_gesture_recognition.py, sense/controller.py, sense/display.py
This PR copies over some general changes from #64 as long as that PR is still on hold.
- Add `font_scale` and `thickness` arguments to the `put_text` method
- Add `DisplayClassnameOverlay` operation that shows detected classes as a big text overlay (see screenshot)
- Fix `int` parsing of `camera_id` in all scripts
- Fix assignment of `runtime_error` in `controller.py` (the `as` statement wasn't working as expected)
If you want to test the `DisplayClassnameOverlay`, add this to the `display_ops` in `run_gesture_recognition.py`:
```python
sense.display.DisplayClassnameOverlay(
thresholds={
"\"Sleeping\" gesture": 0.5,
"Covering ears": 0.5,
"Covering eyes": 0.5,
"Facepalming": 0.5,
"Nodding": 0.5,
"Putting finger to mouth": 0.5,
"Scratching": 0.5,
"Shaking head": 0.5,
"Waving": 0.5,
}
)
``` …
=> Add classname display overlay

sense/feature_extractors/mobilenet.py
This PR removes the step in the pre-processing phase which was causing a confusion between left and right labels during predictions in `gesture_recognition` and `fitness_tracker`.
=> [FIX] Frame flip in pre-processing causing left/right confusion

README.md
Problem: the README makes it look like `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch` is a required installation step. 
A few `sense-iOS` users reported getting confused about this during our last hackathon.  My suggestion is to include the example install command into the `Note:` body to make it clear that this step is not mandatory.
=> README - Edit note about pytorch installation

tools/conversion/convert_to_tflite.py, tools/conversion/keras_converter.py, tools/conversion/section_conversion.py, tools/conversion/weights_loader.py
This PR adds a `--verbose` command-line argument to the TFlite conversion script. When verbose logging is enabled, we set the log level accordingly so that all log messages are shown, including `logging.info()`.
In the PR, I also changed all parameters being passed to `logging.info()` to be well-formatted strings, as logging fails if you pass multiple parameters (this is different to `print(..)` which accepts any number of parameters.
If `--verbose` is not set, the only output is the converted model summary with input and output names. Also, there are always a bunch of tensorflow prints that are unaffected by the new `--verbose` flag.
Example call:
```
python tools/conversion/convert_to_tflite.py \
--backbone=efficientnet \
--classifier=efficient_net_gesture_control \ …
```
=> TFlite Converter: Add `--verbose` argument to show detailed log messages

tools/train_classifier.py
When resuming training from a checkpoint, we were previously only using the trained feature extractor weights, but not the ones for the classifier. This is fixed now.
Furthermore, I added a flag for always overwriting existing files (`--overwrite`) and simplified the code for that check a little bit.
=> Load classifier checkpoint when resuming training

tools/sense_studio/annotation.py
This PR adds an `ignore-case` parameter to natsorted videos and images. Originally, this isn't handled well in the default case.
**Default:**
```
videos = ['video-1', 'video-2', 'Video-1', 'Video-2']
videos = natsorted(videos)
OUTPUT: ['Video-1', 'Video-2', 'video-1', 'video-2']
```
**Case-sensitive:**
```
videos = ['video-1', 'video-2', 'Video-1', 'Video-2']
videos = natsorted(videos, alg=ns.IC)
OUTPUT: ['video-1', 'Video-1', 'video-2', 'Video-2']
```
=> [Fix] Add ignore-case option to "natsorted"

tools/sense_studio/sense_studio.py, tools/sense_studio/static/main.js, tools/sense_studio/static/video_recording.js, tools/sense_studio/templates/video_recording.html, tools/sense_studio/utils.py, tools/sense_studio/video_recording.py
This PR is associated with [this ticket](https://20bn.atlassian.net/browse/AV-4410) and adds a countdown and recording duration in the project config, and has a button to "Save as default".
The project config will now have the following structure:
```
{
"name": ...,
"date": ...,
"classes": ...,
"temporal": ...,
"use_gpu": ...,
--> "video_recording": {
"countdown": 5,
"recording": 3
}
}
```
=> [Feature] Save default timer settings on video-recording page

tools/sense_studio/annotation.py, tools/sense_studio/templates/video_list.html
This PR addresses [this ticket](https://20bn.atlassian.net/browse/AV-4413) and adds a filter option to the list of videos on the `Video Annotation` page. Additionally, it adds a view to display the number of "total", "tagged" and "untagged" videos for the given class, label and split.
=> [Feature] Add filter to video-list page (UI-kit)

tools/sense_studio/annotation.py, tools/sense_studio/project_utils.py, tools/sense_studio/sense_studio.py, tools/sense_studio/static/main.js, tools/sense_studio/templates/projects_overview.html, tools/sense_studio/templates/skeleton.html, tools/sense_studio/utils.py, tools/sense_studio/video_recording.py
Before, it was confusing to have the same input fields and button for both creating new projects and importing existing ones. Now the two have been split and also redesigned to take less space per default.
Furthermore, you previously had to indicate the full path for the project to be created, while the project name was somehow unused. Now the project directory will automatically be created from the project name (with conversion to lower case and replacing spaces).
- The new file `project_utils.py` has been created to bundle all project-related functions
- As part of switching to UIkit, the autocomplete mechanism for path search fields has been re-implemented by using [JavaScript-autoComplete](https://goodies.pixabay.com/javascript/auto-complete/demo.html)
- Form-checks have been added on …
=> Split new project / import and use project name as folder name

tools/sense_studio/annotation.py
This PR fixes the natural sorting of videos from video-list page to the annotation page.
=> [Fix] Sort videos with "natural-sort" while annotating

sense/finetuning.py, tools/sense_studio/static/training.js, tools/sense_studio/templates/training.html, tools/sense_studio/training.py, tools/train_classifier.py
This PR fixes two error cases related to the display of the confusion matrix:
The browser was apparently caching the image of the confusion matrix (given through a URL), so if you ran a training multiple times in the same directory, you would always only see the first confusion matrix.
Now we directly send the binary image in the response from the server, so no URL can be cached.
If you ran another training in an existing checkpoint directory, but cancelled it before the first epoch (or ran a temporal training that doesn't produce a confusion matrix), the interface would still show the confusion matrix from the previous training run.
Now we use an `Event` to check, if a new confusion matrix has actually been produced in this training run.
=> Fix confusion matrix display

tools/sense_studio/templates/training.html
Description;
This PR will fix the issue of `Train Model` button staying active even if the models to choose from are not available on user's system.
=> [Fix] Train model button disabled if no models exist

tools/sense_studio/templates/training.html
Description;
This PR will fix the issue of Train Model button staying active even if the models to choose from are not available on user's system.
It will also show a hint to the user about where to get the models.
=> [Fix] Disable train model button if no models exist

tools/sense_studio/sense_studio.py, tools/sense_studio/static/main.js, tools/sense_studio/templates/projects_overview.html
Thanks for the design update in #156!
There were a few small issues with the previous solution though:
- The project name was shown as the project directory, but actually the name is transformed on the backend before the directory is created (e.g. to avoid spaces in the folder name)
- The shown path would be incorrect on Windows, because it would always append a `/`
- When clearing both input fields, the label would still show a single '/'
Now the proper path handling is done on the backend and all necessary information is transferred to the JS side.
=> Safe path handling in the full path display

sense/camera.py, sense/controller.py, sense/finetuning.py, tests/test_camera.py
Make sure that videos during testing are also presented to the model at the correct frame rate. Currently, they would be read at their original frame rate while assuming it to be the model frame rate, making them look slower or faster.
- The `uniform_frame_sample` method has been extended to also handle the case of upsampling
- A `VideoSource` can now have a `target_fps` defined. If this is given, the video is immediately read and resampled on initialization.
- This same mechanism is now used in both training and testing
- Unit tests for the new behavior have been added
This is a different approach to #155
=> Resample testing videos

sense/finetuning.py, tools/sense_studio/annotation.py, tools/sense_studio/project_tags.py, tools/sense_studio/project_utils.py, tools/sense_studio/sense_studio.py, tools/sense_studio/static/main.css, tools/sense_studio/static/main.js, tools/sense_studio/tags.py, tools/sense_studio/templates/frame_annotation.html, tools/sense_studio/templates/project_details.html, tools/sense_studio/utils.py, tools/train_classifier.py
- Add backwards compatibility update when loading project config
- Setup dictionary of project tags, update class tags and translate existing annotations
- Check for all other project settings that have been added later
- Treat `background` as persistent default label
- Correctly handle tag indices that might have gaps (when tags have been removed), especially when building `label2int` dictionary
- Save `max_tag_index` so that a removed tag can not be overwritten by a new one
- Reset annotations for tags that have been removed
- Let `logreg` work on an arbitrary number of tags
- Don't show "This tag already exists" when leaving a tag name unchanged
- Flip tag name and index in project tags dictionary for easier processing
- Sort tags by value
- Remove duplicate `FileNotFoundErrors`
- Move …
=> Backwards compatibility and missing updates for project tags

sense/finetuning.py, tools/directories.py, tools/sense_studio/annotation.py, tools/sense_studio/sense_studio.py, tools/sense_studio/static/main.js, tools/sense_studio/templates/frame_annotation.html, tools/sense_studio/templates/navigation.html, tools/sense_studio/templates/project_details.html, tools/sense_studio/utils.py
Before, one logistic regression would be trained per class and only on the data of the split (test or validation) that was just submitted. Because tags are now globally defined and can be present in multiple classes, it makes more sense to have one global logistic regression model as well. Also we can use both data from training and validation, because this is just used for assisting the user with annotation.
- `train_logreg` collects data from both splits and all classes
- The call to `compute_frames_and_features` was moved into `train_logreg`, because both calling methods were doing the same operations before
- `train_logreg` was moved into `annotation.py` to prevent the cyclic import `finetuning` -> `utils` -> `finetuning`
- Toggling the `assisted_tagging` flag no longer needs the …
=> Train global logistic regression model on all available data

docs/wiki/gallery.md
This PR adds a preview gif of the word-level American sign language project to the gallery.
=> Add WLASL preview to gallery

README.md
Add information on the expected camera and model FPS to the README, because there has been confusion about which values should be achieved for real-time processing.
Also generalize the instructions on extracting additional resource folders, because now the download contains multiple ones.
Closes #175
=> Add explanation on expected camera and model FPS
