- realtimenet/camera.py
Adding documentation and type hints to the `camera.py` classes.
> Documentation: camera.py

- realtimenet/camera.py
- realtimenet/engine.py
- scripts/run_calorie_estimation.py
- scripts/run_custom_classifier.py
- scripts/run_fitness_rep_counter.py
- scripts/run_fitness_tracker.py
- scripts/run_gesture_recognition.py
This PR addresses [Issue #26](https://github.com/TwentyBN/20bn-realtimenet/issues/26). It adds some inline documentation and type hints to `engine.py`.
> Documentation: engine.py

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
This PR:
- Adds the code of conduct from https://www.contributor-covenant.org/version/2/0/code_of_conduct.html.
- Adds a minimal CONTRIBUTING.md
> Code of Conduct

- scripts/tools/video_capture.py
- Ticket: [AV-3714](https://20bn.atlassian.net/browse/AV-3714)
This PR updates the `video_capture.py` script that can be used to record videos ourselves. 
**Acceptance criteria**:
> Script to record videos yourself

- scripts/tools/video_capture.py
This PR updates the FPS calculated as is in case it's more than 16, or 16 otherwise.
Previously got merged without the updated value.
> VideoCapture script - recorded FPS

- CONTRIBUTING.md
- README.md
Maybe lets use lowercase instead
> switch to lowercase

- requirements.txt
This PR will add missing Flask dependency to `requirements.txt`
> Add flask requirement to requirements.txt

- .gitignore
- scripts/tools/annotation/annotation.py
- scripts/tools/annotation/prepare_annotation.py
- scripts/tools/annotation/templates/up_liste.html
Ticket: https://20bn.atlassian.net/browse/AV-3999
Description:
This PR will add an update to `annotation.py` script to fix the issue of getting index error when all videos are annotated in a folder. Now, as an update after the last video's annotations submission it will redirect to the list of videos page.
> [Feature] AV-3999 : Do not end on index error

- .gitignore
- scripts/tools/annotation/annotation.py
**Ticket**: https://20bn.atlassian.net/browse/AV-3998
**Description:**
This PR will fix the problem of `shape not matching` or the error `This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator` if you click on button `Retrain model`. It will check the annotation if they exist before training on it. For logistic regression, labels will be set iff the relevant classes exists in annotations.
> [Fix] AV-3998: Check annotation before training

- README.md
Made the links relative to the master branch vs the commit hash which might not be valid anymore after the renaming.
> Fix file reference links

- .gitignore
- requirements.txt
- scripts/tools/flip_video.py
Ticket: https://20bn.atlassian.net/browse/AV-3984
Description:
This PR will add a script named `flip_video.py` inside scripts/tools folder. This script will help user to flip their videos horizontally to create more data.
> [Feature] AV-3984: Create script for video flipping horizontally

- scripts/tools/annotation/annotation.py
- scripts/tools/annotation/templates/up_liste.html
Ticket: [AV-3977](https://20bn.atlassian.net/browse/AV-3977)
Description:
This PR will add a feature to show video name above the frames of that video for user information.
> [Feature] AV-3977: Show video name above frames page

- scripts/tools/flip_video.py
This PR will add a fix to `flip_video.py` for `path_in` and `path_out` variable so it can work with relative and absolute path both.
> [Fix] flip_video update 

- scripts/tools/annotation/annotation.py
- scripts/tools/annotation/prepare_annotation.py
This PR makes the code more consistent and robust to handle data-path as a command-line argument. Relative data-path couldn't successfully fetch the frames generated while annotating, which is not always stored as the complete path, irrespective of what the user inputs:
`--data_path=dataset` or `--data_path=/home/user/.../sense/dataset` will both be treated as `--data_path=/home/user/.../sense/dataset`
- reformat code
- clean-up imports
- translate comments from French to English
**Note:** Need docstrings for Flask methods in `annotation.py`.
> [Annotation] Fix: data-path error

- sense/downstream_tasks/nn_utils.py
Add support for sigmoid outputs in the `LogisticRegression` class (not used anywhere yet)
> Add LogisticRegression with sigmoid outputs

- tools/sense_studio/sense_studio.py
Description:
This PR will make running logistic regression on non-tagged videos or on video having only background tags safer, so it will not break the web server.
> [Fix] Make logistic regression safer

- tools/sense_studio/annotation.py
- tools/sense_studio/sense_studio.py
- tools/sense_studio/static/main.js
- tools/sense_studio/templates/frame_annotation.html
This PR links to [this ticket](https://20bn.atlassian.net/browse/AV-4350) and adds the feature to show the saved annotations for a video, if the user has previously annotated it.
> Load existing (saved) annotations for videos

- tools/sense_studio/annotation.py
- tools/sense_studio/static/main.css
- tools/sense_studio/templates/frame_annotation.html
Description:
This PR will create two new buttons Next and Previous on the frame annotations page for users to move around videos without doing annotations.
> [Feature] create navigation buttons on annotations page

- requirements.txt
- tools/sense_studio/annotation.py
- tools/sense_studio/templates/frame_annotation.html
Description:
This PR will add functionality of naturally sorting which will do natural sort on the video list shown to users.
> [Feature] Natural sorting video list

- tools/sense_studio/sense_studio.py
- tools/sense_studio/static/main.js
- tools/sense_studio/static/video_recording.js
- tools/sense_studio/video_recording.py
- Update function `syncRequest` in main.js by adding an optional argument for the HTTP request method (defalt `POST`)
- Update function `recordVideo` to send request to backend for `ffmpeg` installation check and leave an error mesage if it is not installed
- Add function `check_ffmpeg` in video_recording.py to check `ffmpeg` installation
> Check if ffmpeg is installed and leave error message

- tools/sense_studio/static/training.js
Description:
This PR will fix the issue of `OSError: handle is closed` which occurs because of unavailability of the training process object in the request done by socketio.
> [Fix] First training does not start

- sense/finetuning.py
- tools/sense_studio/project_utils.py
- tools/train_classifier.py
Description:
This PR will fix issue of wrong tags names in Lab2Int file for temporal training. 
Issue: 
It was not taking updated tag names of the classes in temporal training. Instead, it was taking `{class_name}_position_1` and `{class_name}_position_2` as tag names.
Update from Guillaume's commit on his branch `feature/ui-kit-smart-tv`.
Link: https://github.com/TwentyBN/sense/commit/fb323f21cee00cac6b8c793d0838763fbf00c10a
> [Fix] Lab2int fix for temporal training

- tools/sense_studio/static/main.css
- tools/sense_studio/static/training.js
- tools/sense_studio/templates/training.html
Description:
This PR will update the training page in sense studio. Below are the changes:
1. It will replace the original input taker for `Number of layers to finetune` with a slider and an output tag beside it for showing the selected layers.
2. The output tag will show `Classification Layer` when selected number of layers to finetune is `0`.
3. It will set default `numberOfLayersToFinetune` value based on the selected model.
> [Feature] Clarify num of layers to finetune

- tools/sense_studio/static/main.js
- tools/sense_studio/templates/projects_overview.html
@YasheshSavani Can you try this and let me know what you think?
> Suggestions about "[Feature] Clarify path for new project"

- tools/sense_studio/static/main.js
- tools/sense_studio/templates/projects_overview.html
Description:
This PR will increase the size of the new project creation card and will add one more disabled field beside the project path to show the project name for which the project folder will be created.
> [Feature] Clarify path for new project

- sense/finetuning.py
- tools/train_classifier.py
- sort `label_names` in `train_classifier.py`
- generate confusion matrix for temporal training in `finetuning.py`
> add confusion matrix for temporal training and sort labels name alphabetically

- sense/finetuning.py
- tools/train_classifier.py
Description:
This PR will add functionality to use classes from project config-if project config exists else use directory names as class labels in training.
> use classes from project config if config exists

- examples/run_action_recognition.py
- examples/run_calorie_estimation.py
- examples/run_fitness_rep_counter.py
- examples/run_fitness_tracker.py
- examples/run_gesture_control.py
- tools/sense_studio/demos.py
Some changes:
- I further updated the kwargs to simplify the function signatures. 
- Typehints throw an error when multiple types are passed in (where `Optional[int, float]`'s were used) -- replaced with just float
> Demos kwargs refactor
